# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-json
    # -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        args: ['--in-place', '--ignore=E501,W504']
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: ['--statistics', '--ignore=F401,F403,F405,F821,F841,E265,E501']
