gridmontage:
  gridspec:
    direction: 'downup'
    zigzag: true
    flip: true
  overlap: 0.1
montage:
  from_serialem_mrc:
    direction: 'downup'
    zigzag: true
    flip: true
    rot90: 3
    flipud: true
    fliplr: false
predicrystal:
  location: 'C:\predicrystal'
  pixel_classification: 'C:\predicrystal\classifiers\normalized_holey_pixel_classification.ilp'
  object_classification: 'C:\predicrystal\classifiers\normalized_holey_object_classification.ilp'
  filter_distance: 2.0
  train_size: 1024
  train_mag: 15
