microscope: fei_themisZ
camera: simulate
calibration: simulate

use_tem_server: False
tem_server_host: 'localhost'
tem_server_port: 8088

indexing_server_exe: 'instamatic.dialsserver.exe'
indexing_server_host: 'localhost'
indexing_server_port: 8089
dials_script: 'E:/cctbx/dials_script.bat'

cred_relax_beam_before_experiment: false
cred_track_stage_positions: false
